"""track_b_schema_updates

Revision ID: c43cb8108df7
Revises: 001
Create Date: 2026-07-27 07:58:20.730239+00:00

"""
from typing import Sequence, Union

from alembic import op
from app.types import GUID
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c43cb8108df7'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_id', GUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=64), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('meta', sa.String(length=1024), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_actor_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'payload')
    op.add_column('dock_slots', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_dock_slots_dock_id'), 'dock_slots', ['dock_id'], unique=False)
    op.drop_constraint(op.f('dock_slots_dock_id_fkey'), 'dock_slots', type_='foreignkey')
    op.drop_constraint(op.f('dock_slots_vehicle_id_fkey'), 'dock_slots', type_='foreignkey')
    op.create_foreign_key(None, 'dock_slots', 'docks', ['dock_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dock_slots', 'vehicle_id')
    op.drop_column('dock_slots', 'is_charging')
    op.add_column('docks', sa.Column('location_lat', sa.Float(), nullable=False))
    op.add_column('docks', sa.Column('location_lng', sa.Float(), nullable=False))
    op.add_column('docks', sa.Column('address', sa.String(length=512), nullable=True))
    op.add_column('docks', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('docks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('docks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('docks', 'status')
    op.drop_column('docks', 'latitude')
    op.drop_column('docks', 'longitude')
    # NOTE: the autogenerated migration this was based on only indexed these
    # three tables — it never created them. Fixed here: create_table added
    # for notifications/ride_events/vehicle_status before their indexes.
    op.create_table(
        'notifications',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('user_id', GUID(), nullable=False),
        sa.Column('type', sa.String(length=30), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('body', sa.String(length=1000), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_refresh_tokens_expiry'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_family'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table(
        'ride_events',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('ride_id', GUID(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['ride_id'], ['rides.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_ride_events_ride_id'), 'ride_events', ['ride_id'], unique=False)
    op.add_column('rides', sa.Column('start_dock_id', GUID(), nullable=False))
    op.add_column('rides', sa.Column('end_dock_id', GUID(), nullable=True))
    op.add_column('rides', sa.Column('ride_token_jti', sa.String(length=64), nullable=True))
    op.add_column('rides', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('rides', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('rides', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('rides', sa.Column('fare_amount', sa.Float(), nullable=True))
    op.add_column('rides', sa.Column('fare_currency', sa.String(length=10), server_default='INR', nullable=False))
    op.add_column('rides', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rides', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'REQUESTED'::character varying"))
    op.alter_column('rides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_index(op.f('ix_rides_user_id'), 'rides', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'rides', ['ride_token_jti'])
    op.drop_constraint(op.f('rides_vehicle_id_fkey'), 'rides', type_='foreignkey')
    op.drop_constraint(op.f('rides_dock_end_id_fkey'), 'rides', type_='foreignkey')
    op.drop_constraint(op.f('rides_dock_start_id_fkey'), 'rides', type_='foreignkey')
    op.drop_constraint(op.f('rides_user_id_fkey'), 'rides', type_='foreignkey')
    op.create_foreign_key(None, 'rides', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rides', 'docks', ['end_dock_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rides', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rides', 'docks', ['start_dock_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('rides', 'fare')
    op.drop_column('rides', 'dock_end_id')
    op.drop_column('rides', 'end_at')
    op.drop_column('rides', 'start_at')
    op.drop_column('rides', 'dock_start_id')
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table(
        'vehicle_status',
        sa.Column('id', GUID(), nullable=False),
        sa.Column('vehicle_id', GUID(), nullable=False),
        sa.Column('battery_pct', sa.Integer(), nullable=True),
        sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_vehicle_status_vehicle_id'), 'vehicle_status', ['vehicle_id'], unique=False)
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('battery_level', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('slot_id', GUID(), nullable=True))
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('vehicles', 'qr_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_unique_constraint(None, 'vehicles', ['slot_id'])
    op.drop_constraint(op.f('vehicles_dock_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'dock_slots', ['slot_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vehicles', 'last_seen_at')
    op.drop_column('vehicles', 'dock_id')
    op.drop_column('vehicles', 'battery_pct')
    op.add_column('wallet_transactions', sa.Column('source', sa.String(length=30), nullable=False))
    op.add_column('wallet_transactions', sa.Column('balance_after', sa.Float(), nullable=False))
    op.add_column('wallet_transactions', sa.Column('note', sa.String(length=512), nullable=True))
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'reference_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_wallet_txn_reference'), table_name='wallet_transactions')
    op.drop_index(op.f('idx_wallet_txn_wallet'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_reference_id'), 'wallet_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_unique_constraint('uq_wallet_txn_reference', 'wallet_transactions', ['reference_id'])
    op.drop_constraint(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_transactions', 'wallets', ['wallet_id'], ['id'], ondelete='RESTRICT')
    op.add_column('wallets', sa.Column('balance', sa.Float(), server_default='0', nullable=False))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('wallets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
    op.alter_column('wallets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('wallets_user_id_key'), 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_user_id_key'), 'wallets', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('wallets', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallets', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'INR'::character varying"))
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'balance')
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_transactions_wallet_id_fkey'), 'wallet_transactions', 'wallets', ['wallet_id'], ['id'])
    op.drop_constraint('uq_wallet_txn_reference', 'wallet_transactions', type_='unique')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_reference_id'), table_name='wallet_transactions')
    op.create_index(op.f('idx_wallet_txn_wallet'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_wallet_txn_reference'), 'wallet_transactions', ['reference_id'], unique=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallet_transactions', 'reference_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('wallet_transactions', 'note')
    op.drop_column('wallet_transactions', 'balance_after')
    op.drop_column('wallet_transactions', 'source')
    op.add_column('vehicles', sa.Column('battery_pct', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('dock_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_dock_id_fkey'), 'vehicles', 'docks', ['dock_id'], ['id'])
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.alter_column('vehicles', 'qr_code',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'slot_id')
    op.drop_column('vehicles', 'battery_level')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_index(op.f('ix_vehicle_status_vehicle_id'), table_name='vehicle_status')
    op.drop_table('vehicle_status')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_phone'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('rides', sa.Column('dock_start_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('dock_end_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('rides', sa.Column('fare', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.create_foreign_key(op.f('rides_user_id_fkey'), 'rides', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('rides_dock_start_id_fkey'), 'rides', 'docks', ['dock_start_id'], ['id'])
    op.create_foreign_key(op.f('rides_dock_end_id_fkey'), 'rides', 'docks', ['dock_end_id'], ['id'])
    op.create_foreign_key(op.f('rides_vehicle_id_fkey'), 'rides', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_constraint(None, 'rides', type_='unique')
    op.drop_index(op.f('ix_rides_user_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.alter_column('rides', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rides', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'REQUESTED'::character varying"))
    op.drop_column('rides', 'updated_at')
    op.drop_column('rides', 'fare_currency')
    op.drop_column('rides', 'fare_amount')
    op.drop_column('rides', 'duration_seconds')
    op.drop_column('rides', 'ended_at')
    op.drop_column('rides', 'started_at')
    op.drop_column('rides', 'ride_token_jti')
    op.drop_column('rides', 'end_dock_id')
    op.drop_column('rides', 'start_dock_id')
    op.drop_index(op.f('ix_ride_events_ride_id'), table_name='ride_events')
    op.drop_table('ride_events')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_family'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_expiry'), 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.add_column('docks', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('docks', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('docks', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('docks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('docks', 'updated_at')
    op.drop_column('docks', 'is_active')
    op.drop_column('docks', 'address')
    op.drop_column('docks', 'location_lng')
    op.drop_column('docks', 'location_lat')
    op.add_column('dock_slots', sa.Column('is_charging', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('dock_slots', sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dock_slots', type_='foreignkey')
    op.create_foreign_key(op.f('dock_slots_vehicle_id_fkey'), 'dock_slots', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('dock_slots_dock_id_fkey'), 'dock_slots', 'docks', ['dock_id'], ['id'])
    op.drop_index(op.f('ix_dock_slots_dock_id'), table_name='dock_slots')
    op.drop_column('dock_slots', 'created_at')
    op.add_column('audit_logs', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_id_fkey'), 'audit_logs', 'users', ['actor_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_logs', 'meta')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'user_id')
    # ### end Alembic commands ###
